from __future__ import annotations
from typing import Protocol, Any

class GraphAdapter(Protocol):
    def get_transaction(self, transaction_id: str) -> dict[str, Any]: ...
    def get_customer(self, customer_id: str) -> dict[str, Any]: ...
    def get_account(self, account_id: str) -> dict[str, Any]: ...
    def get_transaction_history(self, account_id: str) -> list[dict[str, Any]]: ...
    def get_graph_neighborhood(self, entity_id: str, depth: int = 2) -> dict[str, Any]: ...
    def detect_patterns(self, transaction_id: str) -> dict[str, Any]: ...
    def similar_entities(self, entity_id: str) -> list[dict[str, Any]]: ...
